server:
  port: 9090
  servlet:
    context-path: /sp
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: TRACE
    org.opensaml.xmlsec: TRACE
spring:
  security:
    saml2:
      relyingparty:
        registration:
          sp:
            signing.credentials:
              - private-key-location: "classpath:credentials/service-provider-private.key"
                certificate-location: "classpath:credentials/service-provider-certificate.crt"
            identityprovider:
              metadata-uri: https://testlab.au.auth0.com/samlp/metadata/K3ysuWCFE6WH2ne94wjC32WYBfdcU11k
              #entity-id: urn:testlab.au.auth0.com
              #verification.credentials:
              #  - certificate-location: "classpath:credentials/testlab.pem"
              #sso-url: https://testlab.au.auth0.com/samlp/K3ysuWCFE6WH2ne94wjC32WYBfdcU11k
